//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity_projem
{
    using System;
    using System.Collections.Generic;
    
    public partial class kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kitaplar()
        {
            this.ödünç_alma = new HashSet<ödünç_alma>();
        }
    
        public int kitap_id { get; set; }
        public string baslık { get; set; }
        public string yazar { get; set; }
        public Nullable<int> yayınlanma_yılı { get; set; }
        public string tur { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ödünç_alma> ödünç_alma { get; set; }
    }
}
