//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity_projem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ödünç_alma
    {
        public int ödünç_id { get; set; }
        public int uye_id { get; set; }
        public int kitap_id { get; set; }
        public System.DateTime ödünç_tarihi { get; set; }
        public System.DateTime geriGetirme_tarihi { get; set; }
        public Nullable<System.DateTime> getirilen_tarih { get; set; }
    
        public virtual kitaplar kitaplar { get; set; }
        public virtual üyeler üyeler { get; set; }
    }
}
