//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity_projem
{
    using System;
    using System.Collections.Generic;
    
    public partial class üyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public üyeler()
        {
            this.ödünç_alma = new HashSet<ödünç_alma>();
        }
    
        public int uye_id { get; set; }
        public string ilk_ad { get; set; }
        public string son_ad { get; set; }
        public string email { get; set; }
        public string numara { get; set; }
        public Nullable<System.DateTime> uyelik_tarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ödünç_alma> ödünç_alma { get; set; }
    }
}
